# Generated by Django 4.2.4 on 2023-08-11 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='title',
            field=models.CharField(default='Simple task', max_length=255),
        ),
        migrations.AlterField(
            model_name='task',
            name='text',
            field=models.TextField(),
        ),
    ]
